<?php

/**
 * @file
 * Contains htm_custom_harid_authentication.module.
 */

use Drupal\Core\Routing\RouteMatchInterface;

/**
 * Implements hook_help().
 */
function htm_custom_harid_authentication_help($route_name, RouteMatchInterface $route_match) {
  switch ($route_name) {
    // Main module help for the htm_custom_harid_authentication module.
    case 'help.page.htm_custom_harid_authentication':
      $output = '';
      $output .= '<h3>' . t('About') . '</h3>';
      $output .= '<p>' . t('Module for authentication via HarID') . '</p>';
      return $output;

    default:
  }
}
