<?php

/**
 * @file
 * Contains custom_alter_entity_autocomplete.module.
 */

use Drupal\Core\Routing\RouteMatchInterface;
use Drupal\Core\Entity\EntityInterface;
use Drupal\Core\Session\AccountInterface;

/**
 * Implements hook_help().
 */
function custom_alter_entity_autocomplete_help($route_name, RouteMatchInterface $route_match) {
  switch ($route_name) {
    // Main module help for the custom_alter_entity_autocomplete module.
    case 'help.page.custom_alter_entity_autocomplete':
      $output = '';
      $output .= '<h3>' . t('About') . '</h3>';
      $output .= '<p>' . t('Module for altering entity autocomplete') . '</p>';
      return $output;

    default:
  }
}
