<?php

namespace Drupal\htm_custom_translations_new\Form;

use Drupal\Core\Config\Config;
use Drupal\Core\Form\FormStateInterface;

/**
 * Class TranslationFormAddTranslation.
 */
class TranslationFormImport extends TranslationFormBase {
	function actionType()
	{
		return 'import';
	}


	public function buildFormData(array &$form, FormStateInterface $form_state, Config $config, $translation_key)
	{
		$form['upload'] = [
			'#type' => 'file'
		];
	}

	public function validateForm(array &$form, FormStateInterface $form_state)
	{
		$all_files = $this->getRequest()->files->get('files', []);
		#dump($all_files);
		if (!empty($all_files['upload'])) {
			$file_upload = $all_files['upload'];
			$form_state->setValue('upload', $file_upload->getRealPath());
		}

		parent::validateForm($form, $form_state); // TODO: Change the autogenerated stub
	}


}
