cache_tags.settings:
  type: config_object
  label: 'Cache Tags settings'
  mapping:
    CacheTagsName:
      type: string
      label: 'Cache-Tag name'
      translatable: false
    Delimiter:
      type: string
      label: 'Delimiter'
      translatable: false
