<?php


/**
 * Add page title to breadcrumbs
 *
 * @param \Drupal\Core\Breadcrumb\Breadcrumb $breadcrumb
 * @param \Drupal\Core\Routing\RouteMatchInterface $route_match
 * @param array $context
 */
function htm_custom_graphql_functions_system_breadcrumb_alter(\Drupal\Core\Breadcrumb\Breadcrumb &$breadcrumb, \Drupal\Core\Routing\RouteMatchInterface $route_match, array $context){
	if ($breadcrumb && !\Drupal::service('router.admin_context')->isAdminRoute()) {
		$title = \Drupal::service('title_resolver')->getTitle(\Drupal::request(), $route_match->getRouteObject());
		if (!empty($title)) {
			$breadcrumb->addLink(\Drupal\Core\Link::createFromRoute($title, '<none>'));

			//add cache context for full url alias
			$breadcrumb->addCacheContexts(['url']);
		}
	}
}
