<?php

/**
 * @file
 * Contains custom_subscription_notification.
 */

use Drupal\custom_subscription_notification\Controller\NotificationController;
use Drupal\Core\Queue\QueueFactory;
use Drupal\Core\Queue\QueueInterface;
use Drupal\Core\Database\Database;
use Drupal\Component\Utility\Unicode;

/**
 * Implements hook_help().
 */
function custom_subscription_notification_cron() {
        $notification_controller = new NotificationController();

        /** @var QueueFactory $queue_factory */
        $queue_factory = \Drupal::service('queue');
        /** @var QueueInterface $queue */
        $queue = $queue_factory->get('cron_custom_subscription_notification');

        $notificationnodes = $notification_controller->notify();
        foreach($notificationnodes as $notificationnode){
          $queue->createItem($notificationnode);
        }
}

/**
 * Implements hook_mail().
 */
function custom_subscription_notification_mail($key, &$message, $params) {

  $options = array(
      'langcode' => $message['langcode'],
  );
  switch ($key) {
    case 'notification_email':
      $token_service = \Drupal::token();
      $link_root = $params['body']['link_root'];
      $news = $params['body'];

      $title = $token_service->replace($params['subject'], ['clear' => TRUE, 'langcode' => $message['langcode']]);
      $body = $token_service->replace($params['body'], ['clear' => TRUE, 'langcode' => $message['langcode'], 'custom_link_path' => $link_root]);

      $message['headers']['Content-Type'] = 'text/html; charset=UTF-8; format=flowed; delsp=yes';
      $message['from'] = \Drupal::config('system.site')->get('mail');
      $message['subject'] = Unicode::mimeHeaderEncode($title);
			$message['body'][] = nl2br($body);

      break;
  }

}
