<?php

/**
 * @file
 * Contains custom_subscription_notification.
 */

use Drupal\custom_subscription_notification\Controller\NotificationController;
use Drupal\Core\Queue\QueueFactory;
use Drupal\Core\Queue\QueueInterface;
use Drupal\Core\Database\Database;

/**
 * Implements hook_help().
 */
function custom_subscription_notification_cron() {
        $notification_controller = new NotificationController();

        /** @var QueueFactory $queue_factory */
        $queue_factory = \Drupal::service('queue');
        /** @var QueueInterface $queue */
        $queue = $queue_factory->get('cron_custom_subscription_notification');

        $notificationnodes = $notification_controller->notify();
        foreach($notificationnodes as $notificationnode){
          $queue->createItem($notificationnode);
        }
}
