<?php

/**
 * @file
 * Contains custom_study_programme_import.
 */

use Drupal\custom_study_programme_import\Controller\StudyProgrammeController;
use Drupal\Core\Queue\QueueFactory;
use Drupal\Core\Queue\QueueInterface;
use Drupal\Core\Database\Database;

/**
 * Implements hook_help().
 */
function custom_study_programme_import_cron() {
        $import_controller = new StudyProgrammeController();

        /** @var QueueFactory $queue_factory */
        $queue_factory = \Drupal::service('queue');
        /** @var QueueInterface $queue */
        $queue = $queue_factory->get('cron_custom_study_programme_import');

        $programmenodes = $import_controller->import();
        foreach($programmenodes as $programmenode){
          $queue->createItem($programmenode);
        }
}
