jobs:
  build:
    docker:
    - image: alpine:3.7
    steps:
    - run:
        name: Install ssh
        command: |
          apk add openssh
    - add_ssh_keys:
        fingerprints:
          - "3f:b8:bf:43:a8:a2:1e:d1:22:cb:0a:6e:86:4c:cd:04"
    - run:
        name: Enter server
        command: |
          ssh -o StrictHostKeyChecking=no lars@gate.wiseman.ee 'sudo su - wiseman'
          #sudo su - wiseman |
          #ssh -o StrictHostKeyChecking=no core@vm89 |
          #docker ps -a
workflows:
  version: 2
  build:
    jobs:
    - build
version: 2
