jobs:
  build:
    docker:
    - image: alpine:3.7
    steps:
    - run:
        name: Install ssh
        command: |
          apk add openssh
    - add_ssh_keys:
        fingerprints:
          - $SSHFPRINT
    - run:
        name: Enter server and update Drupal
        command: |
          ssh -q -o StrictHostKeyChecking=no $PROXYSERVER -p 222 <<EOF1
          ssh -q -o StrictHostKeyChecking=no $PRELIVESERVER -p 22 <<EOF2
          EOF2
          EOF1
workflows:
  version: 2
  build:
    jobs:
    - build:
version: 2
