jobs:
  lockfile:
    docker:
    - image: node:8.0
    steps:
    - run:
        name: "Checking Versions"
        command: |
          node --version
          npm --version
    - checkout
    - restore_cache:
        keys:
        - v1-dependencies-{{ checksum "package.json" }}
    - run: yarn global add greenkeeper-lockfile@1
    - run: yarn install
    - run: greenkeeper-lockfile-update
    - save_cache:
        paths:
          - node_modules
        key: v1-dependencies-{{ checksum "package.json" }}
    - run: yarn test
    - run: greenkeeper-lockfile-upload
  build:
    docker:
    - image: alpine:3.7
    steps:
    - run:
        name: Install ssh
        command: |
          apk add openssh
    - add_ssh_keys:
        fingerprints:
          - $SSHFPRINT
    - run:
        name: Enter server and update Drupal
        command: |
          ssh -q -o StrictHostKeyChecking=no $PROXYSERVER -p 222 <<EOF1
          ssh -q -o StrictHostKeyChecking=no $PRELIVESERVER -p 22 <<EOF2
          EOF2
          EOF1
workflows:
  version: 2
  build:
    jobs:
    - lockfile
    - build:
        requires:
          - lockfile
        filters:
          tags:
            only: /.*/
          branches:
            only:
              - master
              - /^greenkeeper.*$/
version: 2
