jobs:
  build:
    docker:
    - image: alpine:3.7
    steps:
    - run:
        name: Install ssh
        command: |
          apk add openssh
    - add_ssh_keys:
        fingerprints:
          - $SSHFPRINT
    - run:
        name: Enter servers
        command: |
          ssh -q -o StrictHostKeyChecking=no htm@90.190.106.49 -p 222 <<EOF1
          ls -la
          EOF1
workflows:
  version: 2
  build:
    jobs:
    - build
version: 2
