jobs:
  build:
    docker:
    - image: bash:4.4.19
    steps:
    - run:
        name: Test in local machine
        command: |
          echo $TESTIVARIABLE
workflows:
  version: 2
  build:
    jobs:
    - build
version: 2
