spring:
  kafka:
    consumer:
      auto-offset-reset: earliest
      group-id: liides
    bootstrap-servers: 213.180.8.133:30092

kafka:
  topic:
    request: requests
    response: responses
    logs: logs
    testTopic: htmTestTopic
