FROM eclipse-temurin:17.0.3_7-jre-alpine
VOLUME ["/htmApp", "/htmLogs"]
EXPOSE 8080 8081 8000
WORKDIR /htmApp
ENV JAVA_OPTS="-agentlib:jdwp=transport=dt_socket,server=y,address=8000,suspend=n"
ENV TZ="Europe/Tallinn"
ENTRYPOINT exec java $JAVA_OPTS -jar /htmApp/xRoad-0.0.1-SNAPSHOT.jar