htm_custom_admin_form.customadmin:
  type: config_object
  label: 'Admin configurations'
  mapping:
    general:
      type: mapping
      label: 'General site settings'
      mapping:
        fe-url:
          type: text
          label: 'Front-end url'
    emails:
      type: mapping
      label: 'Email translations'
      mapping:
        email_event_registration:
          type: mapping
          label: 'Event registration email'
          mapping:
            registration_email_subject:
              type: label
              label: 'Registration email subject'
            registration_email_body:
              type: text
              label: 'Registration email body'
            organizer_email_subject:
              type: label
              label: 'Organizer email subject'
            organizer_email_body:
              type: text
              label: 'Organizer email body'
        email_subscription:
          type: mapping
          label: 'Tag subscription emails'
          mapping:
            create_email_subject:
              type: label
              label: 'Create subscription email subject'
            create_email_body:
              type: text
              label: 'Create subscription email body'
            update_email_subject:
              type: label
              label: 'Update subscription email subject'
            update_email_body:
              type: text
              label: 'Update subscription email body'
            notify_email_subject:
              type: label
              label: 'Subscription notification email subject'
            notify_email_body:
              type: text
              label: 'Subscription notification email body'
