<?php

/**
 * @file
 * Contains htm_custom_oska.module.
 */

use Drupal\Core\Routing\RouteMatchInterface;

/**
 * Implements hook_help().
 */
function htm_custom_oska_help($route_name, RouteMatchInterface $route_match) {
  #test
  #teinetest
  #ver 0.4.0
  switch ($route_name) {
    // Main module help for the htm_custom_oska module.
    case 'help.page.htm_custom_oska':
      $output = '';
      $output .= '<h3>' . t('About') . '</h3>';
      $output .= '<p>' . t('Module for OSKA graphs') . '</p>';
      return $output;

    default:
  }
}


function cleanString($text) {
    $text = iconv("UTF-8", "windows-1255", $text);

    $text = str_replace('*','',$text);

    return $text;
}

