<?php

use Drupal\Core\Entity\EntityTypeInterface;
use Drupal\Core\Field\BaseFieldDefinition;
use Drupal\link\LinkItemInterface;


/**
 * Implements hook_entity_base_field_info().
 */
function custom_menu_uri_translation_entity_base_field_info(EntityTypeInterface $entity_type) {
	$fields = [];

	// We modify only menu_link_content entity type.
	if ($entity_type->id() == 'menu_link_content') {

		// Add second link field. This one is translatable.
		$fields['link_override'] = BaseFieldDefinition::create('link')
				->setLabel(t('Link override'))
				->setDescription(t('The location this menu link points to. (translatable version)') . '<br>' . '<strong>'. t('Only overridden if not empty') . '</strong>')
				->setTranslatable(TRUE)
				->setRequired(FALSE)
				->setSettings([
						'link_type' => LinkItemInterface::LINK_GENERIC,
						'title' => DRUPAL_DISABLED,
				])
				->setDisplayOptions('form', [
						'type' => 'link_default',
						'weight' => -2,
				]);
	}

	return $fields;
}