<?php

/**
 * @file
 * Contains import_school_data.module.
 */

use Drupal\import_school_data\Controller\SchoolImportController;
use Drupal\Core\Queue\QueueFactory;
use Drupal\Core\Queue\QueueInterface;

/**
 * Implements hook_cron().
 */
function import_school_data_cron() {
        $import_controller = new SchoolImportController();
        $starttime = time();
        $added = 0;
        $updated = 0;
        $unpublished = 0;

        /** @var QueueFactory $queue_factory */
        $queue_factory = \Drupal::service('queue');
        /** @var QueueInterface $queue */
        $queue = $queue_factory->get('cron_import_school_data');

        $schoolnodes = $import_controller->import();
        foreach($schoolnodes as $schoolnode){
          $queue->createItem($schoolnode);
          if(isset($schoolnode['school_field']['nid'])){
            if($schoolnode['school_field']['status'] == '1'){
              $updated++;
            }else{
              $unpublished++;
            }
          }else{
            $added++;
          }
        }
        $elapsedtime = time() - $starttime;
        $message = t('Tekitatud uued kirjed koolide järjekorda. Lisamisele: @added, Uuendamisele: @updated, Avaldamise lõpetamisele: @unpublished, Kulunud aeg (sekundid): @elapsedtime', array('@added' => $added, '@updated' => $updated, '@unpublished' => $unpublished, '@elapsedtime' => $elapsedtime));
        \Drupal::service('htm_custom_file_logging.write')->write('notice', 'EHIS avaandmetest õppekava uuendamine', $message);
}
