// tslint:disable
export const list = [
  {
    "Nid": "43487",
    "FieldSchoolName": "\u0022Edu Valem\u0022 Erakool",
    "FieldSchoolWebpageAddress": "http:\/\/kool.eraharidus.ee",
    "FieldSchoolContactPhone": "+37258000033",
    "FieldSchoolContactEmail": "kool@eraharidus.ee",
    "FieldSpecialClass": "0",
    "FieldStudentHome": "0",
    "FieldTeachingLanguage": "vene keel",
    "FieldOwnershipType": "Eraomand",
    "FieldEducationalInstitutionTy": "\u00dcldharidusasutus, P\u00f5hikool",
    "FieldAddress": "Tartu mnt 23, Kesklinna linnaosa, Tallinn, Harju maakond",
    "Lat": "59.433569345107",
    "Lon": "24.762786765357",
    "EntityPath": "\/kool\/edu-valem-erakool"
  },
  {
    "Nid": "45084",
    "FieldSchoolName": "\u0022Nikolo\u0022 autokool",
    "FieldSchoolWebpageAddress": "http:\/\/www.aknikolo.ee",
    "FieldSchoolContactPhone": "55585124",
    "FieldSchoolContactEmail": "woodenrobot@hot.ee",
    "FieldSpecialClass": "0",
    "FieldStudentHome": "0",
    "FieldTeachingLanguage": null,
    "FieldOwnershipType": "Eraomand",
    "FieldEducationalInstitutionTy": "T\u00e4ienduskoolitusasutus",
    "FieldAddress": "Viru pst 17a-24, Sillam\u00e4e linn, Ida-Viru maakond",
    "Lat": "59.390978413256",
    "Lon": "27.782651744156",
    "EntityPath": "\/kool\/nikolo-autokool"
  },
  {
    "Nid": "44358",
    "FieldSchoolName": "\u0022Sophie\u0022 koolituskeskus",
    "FieldSchoolWebpageAddress": "http:\/\/www.sophie.ee",
    "FieldSchoolContactPhone": "55551082",
    "FieldSchoolContactEmail": "info@sophie.ee",
    "FieldSpecialClass": "0",
    "FieldStudentHome": "0",
    "FieldTeachingLanguage": null,
    "FieldOwnershipType": "Eraomand",
    "FieldEducationalInstitutionTy": "T\u00e4ienduskoolitusasutus",
    "FieldAddress": "J\u00e4rvek\u00fcla tee 30a, J\u00e4rve linnaosa, Kohtla-J\u00e4rve linn, Ida-Viru maakond",
    "Lat": "59.394669639119",
    "Lon": "27.268188029473",
    "EntityPath": "\/kool\/sophie-koolituskeskus"
  },
  {
    "Nid": "49586",
    "FieldSchoolName": "\u0022Tahanteada\u0022 koolitus",
    "FieldSchoolWebpageAddress": "tahanteada.simplesite.com",
    "FieldSchoolContactPhone": "57826841",
    "FieldSchoolContactEmail": "tahanteada@mail.ee",
    "FieldSpecialClass": "0",
    "FieldStudentHome": "0",
    "FieldTeachingLanguage": null,
    "FieldOwnershipType": "Eraomand",
    "FieldEducationalInstitutionTy": "T\u00e4ienduskoolitusasutus",
    "FieldAddress": "Riisika, R\u00f6a k\u00fcla, Rapla vald, Rapla maakond",
    "Lat": "59.088883015477",
    "Lon": "24.804557990191",
    "EntityPath": "\/kool\/tahanteada-koolitus"
  },
  {
    "Nid": "51776",
    "FieldSchoolName": "1-koolitus mt\u00fc",
    "FieldSchoolWebpageAddress": "www.1koolitus.eu",
    "FieldSchoolContactPhone": "55555942",
    "FieldSchoolContactEmail": "rufet.kerimov@gmail.com, iren@cvp.ee",
    "FieldSpecialClass": "0",
    "FieldStudentHome": "0",
    "FieldTeachingLanguage": null,
    "FieldOwnershipType": "Eraomand",
    "FieldEducationalInstitutionTy": "T\u00e4ienduskoolitusasutus",
    "FieldAddress": "Mustam\u00e4e tee 5, Kristiine linnaosa, Tallinn, Harju maakond",
    "Lat": "59.426592914585",
    "Lon": "24.703399761426",
    "EntityPath": "\/kool\/1-koolitus-mt\u00fc"
  },
  {
    "Nid": "48741",
    "FieldSchoolName": "3D Ekspert Koolituskeskus",
    "FieldSchoolWebpageAddress": "http:\/\/www.3dekspert.ee",
    "FieldSchoolContactPhone": "5037624",
    "FieldSchoolContactEmail": "info@3dekspert.ee",
    "FieldSpecialClass": "0",
    "FieldStudentHome": "0",
    "FieldTeachingLanguage": null,
    "FieldOwnershipType": "Eraomand",
    "FieldEducationalInstitutionTy": "T\u00e4ienduskoolitusasutus",
    "FieldAddress": "Vana-L\u00f5una tn 27, Kesklinna linnaosa, Tallinn, Harju maakond",
    "Lat": "59.421816404681",
    "Lon": "24.745948324744",
    "EntityPath": "\/kool\/3d-ekspert-koolituskeskus"
  },
  {
    "Nid": "43237",
    "FieldSchoolName": "4\/8 Dance Studio",
    "FieldSchoolWebpageAddress": null,
    "FieldSchoolContactPhone": "+372 56 685 313",
    "FieldSchoolContactEmail": "andreiorlov@outlook.com",
    "FieldSpecialClass": "0",
    "FieldStudentHome": "0",
    "FieldTeachingLanguage": null,
    "FieldOwnershipType": "Eraomand",
    "FieldEducationalInstitutionTy": "Huvikool",
    "FieldAddress": "Punane tn 56, Lasnam\u00e4e linnaosa, Tallinn, Harju maakond",
    "Lat": "59.435894733917",
    "Lon": "24.846459281328",
    "EntityPath": "\/kool\/48-dance-studio"
  },
  {
    "Nid": "43352",
    "FieldSchoolName": "4T",
    "FieldSchoolWebpageAddress": "http:\/\/www.4t.ee",
    "FieldSchoolContactPhone": "5254973",
    "FieldSchoolContactEmail": "info@annetiits.eu",
    "FieldSpecialClass": "1",
    "FieldStudentHome": "0",
    "FieldTeachingLanguage": null,
    "FieldOwnershipType": "Eraomand",
    "FieldEducationalInstitutionTy": "T\u00e4ienduskoolitusasutus",
    "FieldAddress": "Tedre tn 81-55, Kristiine linnaosa, Tallinn, Harju maakond",
    "Lat": "59.421103430836",
    "Lon": "24.704273236562",
    "EntityPath": "\/kool\/4t"
  },
  {
    "Nid": "43317",
    "FieldSchoolName": "5MPC",
    "FieldSchoolWebpageAddress": "http:\/\/rillo.ee\/koolitused\/",
    "FieldSchoolContactPhone": "5040260",
    "FieldSchoolContactEmail": "marko@rillo.ee",
    "FieldSpecialClass": "0",
    "FieldStudentHome": "0",
    "FieldTeachingLanguage": null,
    "FieldOwnershipType": "Eraomand",
    "FieldEducationalInstitutionTy": "T\u00e4ienduskoolitusasutus",
    "FieldAddress": null,
    "Lat": null,
    "Lon": null,
    "EntityPath": "\/kool\/5mpc"
  },
  {
    "Nid": "42720",
    "FieldSchoolName": "5T Ohutuse O\u00dc",
    "FieldSchoolWebpageAddress": "http:\/\/5t.ee",
    "FieldSchoolContactPhone": "56670870",
    "FieldSchoolContactEmail": "info@5t.ee",
    "FieldSpecialClass": "0",
    "FieldStudentHome": "0",
    "FieldTeachingLanguage": null,
    "FieldOwnershipType": "Eraomand",
    "FieldEducationalInstitutionTy": "T\u00e4ienduskoolitusasutus",
    "FieldAddress": "Maikellukese tn 7, Kangru alevik, Kiili vald, Harju maakond",
    "Lat": "59.349798056002",
    "Lon": "24.785320229345",
    "EntityPath": "\/kool\/5t-ohutuse-o\u00fc"
  },
  {
    "Nid": "44733",
    "FieldSchoolName": "8feh O\u00dc",
    "FieldSchoolWebpageAddress": "http:\/\/www.harmoonia.webs.com",
    "FieldSchoolContactPhone": "5121864",
    "FieldSchoolContactEmail": "viive.einfeldt@gmail.com",
    "FieldSpecialClass": "0",
    "FieldStudentHome": "0",
    "FieldTeachingLanguage": null,
    "FieldOwnershipType": "Eraomand",
    "FieldEducationalInstitutionTy": "T\u00e4ienduskoolitusasutus",
    "FieldAddress": "P\u00e4rnade pst 9-14, Paikuse alev, P\u00e4rnu linn, P\u00e4rnu maakond",
    "Lat": "58.372069860097",
    "Lon": "24.618584527108",
    "EntityPath": "\/kool\/8feh-o\u00fc"
  },
  {
    "Nid": "43468",
    "FieldSchoolName": "A\u0026E Keeltekool",
    "FieldSchoolWebpageAddress": "http:\/\/www.aekeeltekool.ee",
    "FieldSchoolContactPhone": "+37253463509",
    "FieldSchoolContactEmail": "e.peial@aekeeltekool.ee",
    "FieldSpecialClass": "0",
    "FieldStudentHome": "0",
    "FieldTeachingLanguage": null,
    "FieldOwnershipType": "Eraomand",
    "FieldEducationalInstitutionTy": "Huvikool",
    "FieldAddress": "Liivalaia tn 30-24, Kesklinna linnaosa, Tallinn, Harju maakond",
    "Lat": "59.428661870623",
    "Lon": "24.754502004558",
    "EntityPath": "\/kool\/ae-keeltekool"
  },
  {
    "Nid": "43306",
    "FieldSchoolName": "A\u0026J Lutsari Judokool",
    "FieldSchoolWebpageAddress": "http:\/\/www.aitado.ee",
    "FieldSchoolContactPhone": "5655116",
    "FieldSchoolContactEmail": "aitado@aitado.ee",
    "FieldSpecialClass": "0",
    "FieldStudentHome": "0",
    "FieldTeachingLanguage": null,
    "FieldOwnershipType": "Eraomand",
    "FieldEducationalInstitutionTy": "Huvikool",
    "FieldAddress": "Tondi tn 55, Kristiine linnaosa, Tallinn, Harju maakond",
    "Lat": "59.404868804982",
    "Lon": "24.718393941476",
    "EntityPath": "\/kool\/aj-lutsari-judokool"
  },
  {
    "Nid": "42650",
    "FieldSchoolName": "A+ AUTOKOOL O\u00dc",
    "FieldSchoolWebpageAddress": " a.autokool.oy@eesti.ee",
    "FieldSchoolContactPhone": "5100704",
    "FieldSchoolContactEmail": " a.autokool.oy@eesti.ee",
    "FieldSpecialClass": "0",
    "FieldStudentHome": "0",
    "FieldTeachingLanguage": null,
    "FieldOwnershipType": "Eraomand",
    "FieldEducationalInstitutionTy": "T\u00e4ienduskoolitusasutus",
    "FieldAddress": "Kaasiku tn 9, Liikva k\u00fcla, Harku vald, Harju maakond",
    "Lat": "59.420933460862",
    "Lon": "24.431614125905",
    "EntityPath": "\/kool\/autokool-o\u00fc"
  },
  {
    "Nid": "52362",
    "FieldSchoolName": "A-TVERDOVSKI O\u00dc",
    "FieldSchoolWebpageAddress": "www.tverdovski.ee",
    "FieldSchoolContactPhone": "51920895",
    "FieldSchoolContactEmail": "tverdovskiou@gmail.com",
    "FieldSpecialClass": "0",
    "FieldStudentHome": "0",
    "FieldTeachingLanguage": null,
    "FieldOwnershipType": "Eraomand",
    "FieldEducationalInstitutionTy": "T\u00e4ienduskoolitusasutus",
    "FieldAddress": "Kadaka tee 165-55, Mustam\u00e4e linnaosa, Tallinn, Harju maakond",
    "Lat": "59.405873607904",
    "Lon": "24.660258865766",
    "EntityPath": "\/kool\/tverdovski-o\u00fc"
  },
  {
    "Nid": "44213",
    "FieldSchoolName": "A.K.V.Koolitus",
    "FieldSchoolWebpageAddress": "http:\/\/www.akvkoolitus.ee",
    "FieldSchoolContactPhone": "5284322",
    "FieldSchoolContactEmail": "afanasjeva.kiira@gmail.com",
    "FieldSpecialClass": "0",
    "FieldStudentHome": "0",
    "FieldTeachingLanguage": null,
    "FieldOwnershipType": "Eraomand",
    "FieldEducationalInstitutionTy": "T\u00e4ienduskoolitusasutus",
    "FieldAddress": "Kaare tn 21-23, J\u00f5hvi linn, J\u00f5hvi vald, Ida-Viru maakond",
    "Lat": "59.348799262952",
    "Lon": "27.410879825555",
    "EntityPath": "\/kool\/akvkoolitus"
  },
  {
    "Nid": "44868",
    "FieldSchoolName": "A.P. Vene keele kursused O\u00dc",
    "FieldSchoolWebpageAddress": null,
    "FieldSchoolContactPhone": "53444542",
    "FieldSchoolContactEmail": "annikapiho1@gmail.com",
    "FieldSpecialClass": "0",
    "FieldStudentHome": "0",
    "FieldTeachingLanguage": null,
    "FieldOwnershipType": "Eraomand",
    "FieldEducationalInstitutionTy": "T\u00e4ienduskoolitusasutus",
    "FieldAddress": "Lepiku tn 12, Rakvere linn, L\u00e4\u00e4ne-Viru maakond",
    "Lat": "59.336260465293",
    "Lon": "26.369982401715",
    "EntityPath": "\/kool\/ap-vene-keele-kursused-o\u00fc"
  },
  {
    "Nid": "52406",
    "FieldSchoolName": "A2 Autokool",
    "FieldSchoolWebpageAddress": "www.a2autokool.ee",
    "FieldSchoolContactPhone": "55988598",
    "FieldSchoolContactEmail": "duzits.jekaterina@gmail.com",
    "FieldSpecialClass": "0",
    "FieldStudentHome": "0",
    "FieldTeachingLanguage": null,
    "FieldOwnershipType": "Eraomand",
    "FieldEducationalInstitutionTy": "T\u00e4ienduskoolitusasutus",
    "FieldAddress": "Uus-Muuga pst 7, Maardu linn, Harju maakond",
    "Lat": "59.479177456588",
    "Lon": "24.958488302442",
    "EntityPath": "\/kool\/a2-autokool"
  },
  {
    "Nid": "49558",
    "FieldSchoolName": "AASK Consult O\u00dc",
    "FieldSchoolWebpageAddress": "http:\/\/www.aask.ee",
    "FieldSchoolContactPhone": "3725066662",
    "FieldSchoolContactEmail": "aino.kuntsel@aask.ee",
    "FieldSpecialClass": "0",
    "FieldStudentHome": "0",
    "FieldTeachingLanguage": null,
    "FieldOwnershipType": "Eraomand",
    "FieldEducationalInstitutionTy": "T\u00e4ienduskoolitusasutus",
    "FieldAddress": "Eva ringtee 30, Merem\u00f5isa k\u00fcla, L\u00e4\u00e4ne-Harju vald, Harju maakond",
    "Lat": "59.385664347262",
    "Lon": "24.252218094372",
    "EntityPath": "\/kool\/aask-consult-o\u00fc-0"
  },
  {
    "Nid": "43869",
    "FieldSchoolName": "AB Testudo O\u00dc",
    "FieldSchoolWebpageAddress": "http:\/\/www.testudo.ee",
    "FieldSchoolContactPhone": "5110164",
    "FieldSchoolContactEmail": "info@testudo.ee",
    "FieldSpecialClass": "0",
    "FieldStudentHome": "0",
    "FieldTeachingLanguage": null,
    "FieldOwnershipType": "Eraomand",
    "FieldEducationalInstitutionTy": "T\u00e4ienduskoolitusasutus",
    "FieldAddress": "R\u00e4itsaka tn 13, Haabersti linnaosa, Tallinn, Harju maakond",
    "Lat": "59.42468774623",
    "Lon": "24.674645217587",
    "EntityPath": "\/kool\/ab-testudo-o\u00fc"
  },
  {
    "Nid": "43766",
    "FieldSchoolName": "ABCKEELTEKOOL",
    "FieldSchoolWebpageAddress": "http:\/\/www.abckeeltekool.ee",
    "FieldSchoolContactPhone": "56181828",
    "FieldSchoolContactEmail": "info@abckeeltekool.ee",
    "FieldSpecialClass": "0",
    "FieldStudentHome": "0",
    "FieldTeachingLanguage": null,
    "FieldOwnershipType": "Eraomand",
    "FieldEducationalInstitutionTy": "T\u00e4ienduskoolitusasutus",
    "FieldAddress": "Mere pst 5, Kesklinna linnaosa, Tallinn, Harju maakond",
    "Lat": "59.438527361028",
    "Lon": "24.752939845973",
    "EntityPath": "\/kool\/abckeeltekool"
  },
  {
    "Nid": "51067",
    "FieldSchoolName": "ABCKOOL",
    "FieldSchoolWebpageAddress": "www.abckool.ee",
    "FieldSchoolContactPhone": "56181828",
    "FieldSchoolContactEmail": "info@abckool.ee",
    "FieldSpecialClass": "0",
    "FieldStudentHome": "0",
    "FieldTeachingLanguage": null,
    "FieldOwnershipType": "Eraomand",
    "FieldEducationalInstitutionTy": "T\u00e4ienduskoolitusasutus",
    "FieldAddress": "Tartu mnt 16b, Kesklinna linnaosa, Tallinn, Harju maakond",
    "Lat": "59.433493358897",
    "Lon": "24.761956857711",
    "EntityPath": "\/kool\/abckool"
  },
  {
    "Nid": "43741",
    "FieldSchoolName": "ABConsult \u00d5ppekeskus",
    "FieldSchoolWebpageAddress": "http:\/\/academy.abconsult.ee\/et\/",
    "FieldSchoolContactPhone": "6261138",
    "FieldSchoolContactEmail": "info@abconsult.ee",
    "FieldSpecialClass": "0",
    "FieldStudentHome": "0",
    "FieldTeachingLanguage": null,
    "FieldOwnershipType": "Eraomand",
    "FieldEducationalInstitutionTy": "T\u00e4ienduskoolitusasutus",
    "FieldAddress": "J\u00f5e tn 5, Kesklinna linnaosa, Tallinn, Harju maakond",
    "Lat": "59.438258408026",
    "Lon": "24.763790280327",
    "EntityPath": "\/kool\/abconsult-\u00f5ppekeskus"
  },
  {
    "Nid": "42644",
    "FieldSchoolName": "ALR Arengukeskus MT\u00dc",
    "FieldSchoolWebpageAddress": "http:\/\/www.alr.ee",
    "FieldSchoolContactPhone": "56690105",
    "FieldSchoolContactEmail": "info@alr.ee",
    "FieldSpecialClass": "0",
    "FieldStudentHome": "0",
    "FieldTeachingLanguage": null,
    "FieldOwnershipType": "Eraomand",
    "FieldEducationalInstitutionTy": "T\u00e4ienduskoolitusasutus",
    "FieldAddress": "P\u00e4eva tee 6, Naage k\u00fcla, Harku vald, Harju maakond",
    "Lat": "59.412413946998",
    "Lon": "24.35367117816",
    "EntityPath": "\/kool\/alr-arengukeskus-mt\u00fc"
  }
];