// tslint:disable
export const list = [
	{
		Nid: '43487',
		title: '\u0022Edu Valem\u0022 Erakool',
		fieldSchoolWebpageAddress: 'http://kool.eraharidus.ee',
		fieldSchoolContactPhone: '+37258000033',
		fieldSchoolContactEmail: 'kool@eraharidus.ee',
		fieldSpecialClass: '0',
		fieldStudentHome: '0',
		fieldTeachingLanguage: 'vene keel',
		fieldOwnershipType: 'Eraomand',
		fieldEducationalInstitutionTy: '\u00dcldharidusasutus, P\u00f5hikool',
		fieldAddress: [
			{
				fieldAddress:
					'Tartu mnt 23, Kesklinna linnaosa, Tallinn, Harju maakond',
			},
		],
		Lat: '59.433569345107',
		Lon: '24.762786765357',
		EntityPath: '/kool/edu-valem-erakool',
	},
	{
		Nid: '45084',
		title: '\u0022Nikolo\u0022 autokool',
		fieldSchoolWebpageAddress: 'http://www.aknikolo.ee',
		fieldSchoolContactPhone: '55585124',
		fieldSchoolContactEmail: 'woodenrobot@hot.ee',
		fieldSpecialClass: '0',
		fieldStudentHome: '0',
		fieldTeachingLanguage: null,
		fieldOwnershipType: 'Eraomand',
		fieldEducationalInstitutionTy: 'T\u00e4ienduskoolitusasutus',
		fieldAddress: [
			{ fieldAddress: 'Viru pst 17a-24, Sillam\u00e4e linn, Ida-Viru maakond' },
		],
		Lat: '59.390978413256',
		Lon: '27.782651744156',
		EntityPath: '/kool/nikolo-autokool',
	},
	{
		Nid: '44358',
		title: '\u0022Sophie\u0022 koolituskeskus',
		fieldSchoolWebpageAddress: 'http://www.sophie.ee',
		fieldSchoolContactPhone: '55551082',
		fieldSchoolContactEmail: 'info@sophie.ee',
		fieldSpecialClass: '0',
		fieldStudentHome: '0',
		fieldTeachingLanguage: null,
		fieldOwnershipType: 'Eraomand',
		fieldEducationalInstitutionTy: 'T\u00e4ienduskoolitusasutus',
		fieldAddress: [
			{
				fieldAddress:
					'J\u00e4rvek\u00fcla tee 30a, J\u00e4rve linnaosa, Kohtla-J\u00e4rve linn, Ida-Viru maakond',
			},
		],
		Lat: '59.394669639119',
		Lon: '27.268188029473',
		EntityPath: '/kool/sophie-koolituskeskus',
	},
	{
		Nid: '49586',
		title: '\u0022Tahanteada\u0022 koolitus',
		fieldSchoolWebpageAddress: 'tahanteada.simplesite.com',
		fieldSchoolContactPhone: '57826841',
		fieldSchoolContactEmail: 'tahanteada@mail.ee',
		fieldSpecialClass: '0',
		fieldStudentHome: '0',
		fieldTeachingLanguage: null,
		fieldOwnershipType: 'Eraomand',
		fieldEducationalInstitutionTy: 'T\u00e4ienduskoolitusasutus',
		fieldAddress: [
			{
				fieldAddress: 'Riisika, R\u00f6a k\u00fcla, Rapla vald, Rapla maakond',
			},
		],
		Lat: '59.088883015477',
		Lon: '24.804557990191',
		EntityPath: '/kool/tahanteada-koolitus',
	},
	{
		Nid: '51776',
		title: '1-koolitus mt\u00fc',
		fieldSchoolWebpageAddress: 'www.1koolitus.eu',
		fieldSchoolContactPhone: '55555942',
		fieldSchoolContactEmail: 'rufet.kerimov@gmail.com, iren@cvp.ee',
		fieldSpecialClass: '0',
		fieldStudentHome: '0',
		fieldTeachingLanguage: null,
		fieldOwnershipType: 'Eraomand',
		fieldEducationalInstitutionTy: 'T\u00e4ienduskoolitusasutus',
		fieldAddress: [
			{
				fieldAddress:
					'Mustam\u00e4e tee 5, Kristiine linnaosa, Tallinn, Harju maakond',
			},
		],
		Lat: '59.426592914585',
		Lon: '24.703399761426',
		EntityPath: '/kool/1-koolitus-mt\u00fc',
	},
	{
		Nid: '48741',
		title: '3D Ekspert Koolituskeskus',
		fieldSchoolWebpageAddress: 'http://www.3dekspert.ee',
		fieldSchoolContactPhone: '5037624',
		fieldSchoolContactEmail: 'info@3dekspert.ee',
		fieldSpecialClass: '0',
		fieldStudentHome: '0',
		fieldTeachingLanguage: null,
		fieldOwnershipType: 'Eraomand',
		fieldEducationalInstitutionTy: 'T\u00e4ienduskoolitusasutus',
		fieldAddress: [
			{
				fieldAddress:
					'Vana-L\u00f5una tn 27, Kesklinna linnaosa, Tallinn, Harju maakond',
			},
		],
		Lat: '59.421816404681',
		Lon: '24.745948324744',
		EntityPath: '/kool/3d-ekspert-koolituskeskus',
	},
	{
		Nid: '43237',
		title: '4/8 Dance Studio',
		fieldSchoolWebpageAddress: null,
		fieldSchoolContactPhone: '+372 56 685 313',
		fieldSchoolContactEmail: 'andreiorlov@outlook.com',
		fieldSpecialClass: '0',
		fieldStudentHome: '0',
		fieldTeachingLanguage: null,
		fieldOwnershipType: 'Eraomand',
		fieldEducationalInstitutionTy: 'Huvikool',
		fieldAddress: [
			{
				fieldAddress:
					'Punane tn 56, Lasnam\u00e4e linnaosa, Tallinn, Harju maakond',
			},
		],
		Lat: '59.435894733917',
		Lon: '24.846459281328',
		EntityPath: '/kool/48-dance-studio',
	},
	{
		Nid: '43352',
		title: '4T',
		fieldSchoolWebpageAddress: 'http://www.4t.ee',
		fieldSchoolContactPhone: '5254973',
		fieldSchoolContactEmail: 'info@annetiits.eu',
		fieldSpecialClass: '1',
		fieldStudentHome: '0',
		fieldTeachingLanguage: null,
		fieldOwnershipType: 'Eraomand',
		fieldEducationalInstitutionTy: 'T\u00e4ienduskoolitusasutus',
		fieldAddress: [
			{
				fieldAddress:
					'Tedre tn 81-55, Kristiine linnaosa, Tallinn, Harju maakond',
			},
		],
		Lat: '59.421103430836',
		Lon: '24.704273236562',
		EntityPath: '/kool/4t',
	},
	{
		Nid: '43317',
		title: '5MPC',
		fieldSchoolWebpageAddress: 'http://rillo.ee/koolitused/',
		fieldSchoolContactPhone: '5040260',
		fieldSchoolContactEmail: 'marko@rillo.ee',
		fieldSpecialClass: '0',
		fieldStudentHome: '0',
		fieldTeachingLanguage: null,
		fieldOwnershipType: 'Eraomand',
		fieldEducationalInstitutionTy: 'T\u00e4ienduskoolitusasutus',
		fieldAddress: [{ fieldAddress: null }],
		Lat: null,
		Lon: null,
		EntityPath: '/kool/5mpc',
	},
	{
		Nid: '42720',
		title: '5T Ohutuse O\u00dc',
		fieldSchoolWebpageAddress: 'http://5t.ee',
		fieldSchoolContactPhone: '56670870',
		fieldSchoolContactEmail: 'info@5t.ee',
		fieldSpecialClass: '0',
		fieldStudentHome: '0',
		fieldTeachingLanguage: null,
		fieldOwnershipType: 'Eraomand',
		fieldEducationalInstitutionTy: 'T\u00e4ienduskoolitusasutus',
		fieldAddress: [
			{
				fieldAddress:
					'Maikellukese tn 7, Kangru alevik, Kiili vald, Harju maakond',
			},
		],
		Lat: '59.349798056002',
		Lon: '24.785320229345',
		EntityPath: '/kool/5t-ohutuse-o\u00fc',
	},
	{
		Nid: '44733',
		title: '8feh O\u00dc',
		fieldSchoolWebpageAddress: 'http://www.harmoonia.webs.com',
		fieldSchoolContactPhone: '5121864',
		fieldSchoolContactEmail: 'viive.einfeldt@gmail.com',
		fieldSpecialClass: '0',
		fieldStudentHome: '0',
		fieldTeachingLanguage: null,
		fieldOwnershipType: 'Eraomand',
		fieldEducationalInstitutionTy: 'T\u00e4ienduskoolitusasutus',
		fieldAddress: [
			{
				fieldAddress:
					'P\u00e4rnade pst 9-14, Paikuse alev, P\u00e4rnu linn, P\u00e4rnu maakond',
			},
		],
		Lat: '58.372069860097',
		Lon: '24.618584527108',
		EntityPath: '/kool/8feh-o\u00fc',
	},
	{
		Nid: '43468',
		title: 'A\u0026E Keeltekool',
		fieldSchoolWebpageAddress: 'http://www.aekeeltekool.ee',
		fieldSchoolContactPhone: '+37253463509',
		fieldSchoolContactEmail: 'e.peial@aekeeltekool.ee',
		fieldSpecialClass: '0',
		fieldStudentHome: '0',
		fieldTeachingLanguage: null,
		fieldOwnershipType: 'Eraomand',
		fieldEducationalInstitutionTy: 'Huvikool',
		fieldAddress: [
			{
				fieldAddress:
					'Liivalaia tn 30-24, Kesklinna linnaosa, Tallinn, Harju maakond',
			},
		],
		Lat: '59.428661870623',
		Lon: '24.754502004558',
		EntityPath: '/kool/ae-keeltekool',
	},
	{
		Nid: '43306',
		title: 'A\u0026J Lutsari Judokool',
		fieldSchoolWebpageAddress: 'http://www.aitado.ee',
		fieldSchoolContactPhone: '5655116',
		fieldSchoolContactEmail: 'aitado@aitado.ee',
		fieldSpecialClass: '0',
		fieldStudentHome: '0',
		fieldTeachingLanguage: null,
		fieldOwnershipType: 'Eraomand',
		fieldEducationalInstitutionTy: 'Huvikool',
		fieldAddress: [
			{
				fieldAddress: 'Tondi tn 55, Kristiine linnaosa, Tallinn, Harju maakond',
			},
		],
		Lat: '59.404868804982',
		Lon: '24.718393941476',
		EntityPath: '/kool/aj-lutsari-judokool',
	},
	{
		Nid: '42650',
		title: 'A+ AUTOKOOL O\u00dc',
		fieldSchoolWebpageAddress: ' a.autokool.oy@eesti.ee',
		fieldSchoolContactPhone: '5100704',
		fieldSchoolContactEmail: ' a.autokool.oy@eesti.ee',
		fieldSpecialClass: '0',
		fieldStudentHome: '0',
		fieldTeachingLanguage: null,
		fieldOwnershipType: 'Eraomand',
		fieldEducationalInstitutionTy: 'T\u00e4ienduskoolitusasutus',
		fieldAddress: [
			{
				fieldAddress:
					'Kaasiku tn 9, Liikva k\u00fcla, Harku vald, Harju maakond',
			},
		],
		Lat: '59.420933460862',
		Lon: '24.431614125905',
		EntityPath: '/kool/autokool-o\u00fc',
	},
	{
		Nid: '52362',
		title: 'A-TVERDOVSKI O\u00dc',
		fieldSchoolWebpageAddress: 'www.tverdovski.ee',
		fieldSchoolContactPhone: '51920895',
		fieldSchoolContactEmail: 'tverdovskiou@gmail.com',
		fieldSpecialClass: '0',
		fieldStudentHome: '0',
		fieldTeachingLanguage: null,
		fieldOwnershipType: 'Eraomand',
		fieldEducationalInstitutionTy: 'T\u00e4ienduskoolitusasutus',
		fieldAddress: [
			{
				fieldAddress:
					'Kadaka tee 165-55, Mustam\u00e4e linnaosa, Tallinn, Harju maakond',
			},
		],
		Lat: '59.405873607904',
		Lon: '24.660258865766',
		EntityPath: '/kool/tverdovski-o\u00fc',
	},
	{
		Nid: '44213',
		title: 'A.K.V.Koolitus',
		fieldSchoolWebpageAddress: 'http://www.akvkoolitus.ee',
		fieldSchoolContactPhone: '5284322',
		fieldSchoolContactEmail: 'afanasjeva.kiira@gmail.com',
		fieldSpecialClass: '0',
		fieldStudentHome: '0',
		fieldTeachingLanguage: null,
		fieldOwnershipType: 'Eraomand',
		fieldEducationalInstitutionTy: 'T\u00e4ienduskoolitusasutus',
		fieldAddress: [
			{
				fieldAddress:
					'Kaare tn 21-23, J\u00f5hvi linn, J\u00f5hvi vald, Ida-Viru maakond',
			},
		],
		Lat: '59.348799262952',
		Lon: '27.410879825555',
		EntityPath: '/kool/akvkoolitus',
	},
	{
		Nid: '44868',
		title: 'A.P. Vene keele kursused O\u00dc',
		fieldSchoolWebpageAddress: null,
		fieldSchoolContactPhone: '53444542',
		fieldSchoolContactEmail: 'annikapiho1@gmail.com',
		fieldSpecialClass: '0',
		fieldStudentHome: '0',
		fieldTeachingLanguage: null,
		fieldOwnershipType: 'Eraomand',
		fieldEducationalInstitutionTy: 'T\u00e4ienduskoolitusasutus',
		fieldAddress: [
			{
				fieldAddress:
					'Lepiku tn 12, Rakvere linn, L\u00e4\u00e4ne-Viru maakond',
			},
		],
		Lat: '59.336260465293',
		Lon: '26.369982401715',
		EntityPath: '/kool/ap-vene-keele-kursused-o\u00fc',
	},
	{
		Nid: '52406',
		title: 'A2 Autokool',
		fieldSchoolWebpageAddress: 'www.a2autokool.ee',
		fieldSchoolContactPhone: '55988598',
		fieldSchoolContactEmail: 'duzits.jekaterina@gmail.com',
		fieldSpecialClass: '0',
		fieldStudentHome: '0',
		fieldTeachingLanguage: null,
		fieldOwnershipType: 'Eraomand',
		fieldEducationalInstitutionTy: 'T\u00e4ienduskoolitusasutus',
		fieldAddress: [
			{ fieldAddress: 'Uus-Muuga pst 7, Maardu linn, Harju maakond' },
		],
		Lat: '59.479177456588',
		Lon: '24.958488302442',
		EntityPath: '/kool/a2-autokool',
	},
	{
		Nid: '49558',
		title: 'AASK Consult O\u00dc',
		fieldSchoolWebpageAddress: 'http://www.aask.ee',
		fieldSchoolContactPhone: '3725066662',
		fieldSchoolContactEmail: 'aino.kuntsel@aask.ee',
		fieldSpecialClass: '0',
		fieldStudentHome: '0',
		fieldTeachingLanguage: null,
		fieldOwnershipType: 'Eraomand',
		fieldEducationalInstitutionTy: 'T\u00e4ienduskoolitusasutus',
		fieldAddress: [
			{
				fieldAddress:
					'Eva ringtee 30, Merem\u00f5isa k\u00fcla, L\u00e4\u00e4ne-Harju vald, Harju maakond',
			},
		],
		Lat: '59.385664347262',
		Lon: '24.252218094372',
		EntityPath: '/kool/aask-consult-o\u00fc-0',
	},
	{
		Nid: '43869',
		title: 'AB Testudo O\u00dc',
		fieldSchoolWebpageAddress: 'http://www.testudo.ee',
		fieldSchoolContactPhone: '5110164',
		fieldSchoolContactEmail: 'info@testudo.ee',
		fieldSpecialClass: '0',
		fieldStudentHome: '0',
		fieldTeachingLanguage: null,
		fieldOwnershipType: 'Eraomand',
		fieldEducationalInstitutionTy: 'T\u00e4ienduskoolitusasutus',
		fieldAddress: [
			{
				fieldAddress:
					'R\u00e4itsaka tn 13, Haabersti linnaosa, Tallinn, Harju maakond',
			},
		],
		Lat: '59.42468774623',
		Lon: '24.674645217587',
		EntityPath: '/kool/ab-testudo-o\u00fc',
	},
	{
		Nid: '43766',
		title: 'ABCKEELTEKOOL',
		fieldSchoolWebpageAddress: 'http://www.abckeeltekool.ee',
		fieldSchoolContactPhone: '56181828',
		fieldSchoolContactEmail: 'info@abckeeltekool.ee',
		fieldSpecialClass: '0',
		fieldStudentHome: '0',
		fieldTeachingLanguage: null,
		fieldOwnershipType: 'Eraomand',
		fieldEducationalInstitutionTy: 'T\u00e4ienduskoolitusasutus',
		fieldAddress: [
			{
				fieldAddress: 'Mere pst 5, Kesklinna linnaosa, Tallinn, Harju maakond',
			},
		],
		Lat: '59.438527361028',
		Lon: '24.752939845973',
		EntityPath: '/kool/abckeeltekool',
	},
	{
		Nid: '51067',
		title: 'ABCKOOL',
		fieldSchoolWebpageAddress: 'www.abckool.ee',
		fieldSchoolContactPhone: '56181828',
		fieldSchoolContactEmail: 'info@abckool.ee',
		fieldSpecialClass: '0',
		fieldStudentHome: '0',
		fieldTeachingLanguage: null,
		fieldOwnershipType: 'Eraomand',
		fieldEducationalInstitutionTy: 'T\u00e4ienduskoolitusasutus',
		fieldAddress: [
			{
				fieldAddress:
					'Tartu mnt 16b, Kesklinna linnaosa, Tallinn, Harju maakond',
			},
		],
		Lat: '59.433493358897',
		Lon: '24.761956857711',
		EntityPath: '/kool/abckool',
	},
	{
		Nid: '43741',
		title: 'ABConsult \u00d5ppekeskus',
		fieldSchoolWebpageAddress: 'http://academy.abconsult.ee/et/',
		fieldSchoolContactPhone: '6261138',
		fieldSchoolContactEmail: 'info@abconsult.ee',
		fieldSpecialClass: '0',
		fieldStudentHome: '0',
		fieldTeachingLanguage: null,
		fieldOwnershipType: 'Eraomand',
		fieldEducationalInstitutionTy: 'T\u00e4ienduskoolitusasutus',
		fieldAddress: [
			{
				fieldAddress:
					'J\u00f5e tn 5, Kesklinna linnaosa, Tallinn, Harju maakond',
			},
		],
		Lat: '59.438258408026',
		Lon: '24.763790280327',
		EntityPath: '/kool/abconsult-\u00f5ppekeskus',
	},
	{
		Nid: '42644',
		title: 'ALR Arengukeskus MT\u00dc',
		fieldSchoolWebpageAddress: 'http://www.alr.ee',
		fieldSchoolContactPhone: '56690105',
		fieldSchoolContactEmail: 'info@alr.ee',
		fieldSpecialClass: '0',
		fieldStudentHome: '0',
		fieldTeachingLanguage: null,
		fieldOwnershipType: 'Eraomand',
		fieldEducationalInstitutionTy: 'T\u00e4ienduskoolitusasutus',
		fieldAddress: [
			{
				fieldAddress:
					'P\u00e4eva tee 6, Naage k\u00fcla, Harku vald, Harju maakond',
			},
		],
		Lat: '59.412413946998',
		Lon: '24.35367117816',
		EntityPath: '/kool/alr-arengukeskus-mt\u00fc',
	},
];
