<?php

/**
 * @file
 * Contains htm_custom_study_programme_import.
 */

use Drupal\htm_custom_study_programme_import\Controller\StudyProgrammeController;
use Drupal\Core\Queue\QueueFactory;
use Drupal\Core\Queue\QueueInterface;

/**
 * Implements hook_cron().
 */
function htm_custom_study_programme_import_cron() {
        $import_controller = new StudyProgrammeController();
        $starttime = time();
        $added = 0;
        $updated = 0;
        $unpublished = 0;

        /** @var QueueFactory $queue_factory */
        $queue_factory = \Drupal::service('queue');
        /** @var QueueInterface $queue */
        $queue = $queue_factory->get('cron_htm_custom_study_programme_import');

        $programmenodes = $import_controller->import();
        foreach($programmenodes as $programmenode){
          $queue->createItem($programmenode);
          if(isset($programmenode['programme_field']['nid'])){
            if(isset($programmenode['programme_field']['status']) && $programmenode['programme_field']['status'] === '1'){
              $updated++;
            }else{
              $unpublished++;
            }
          }else{
            $added++;
          }
        }
        $elapsedtime = time() - $starttime;
        $message = t('Tekitatud uued kirjed õppekavade järjekorda. Lisamisele: @added, Uuendamisele: @updated, Avaldamise lõpetamisele: @unpublished, Kulunud aeg (sekundid): @elapsedtime', array('@added' => $added, '@updated' => $updated, '@unpublished' => $unpublished, '@elapsedtime' => $elapsedtime));
        \Drupal::service('htm_custom_file_logging.write')->write('notice', 'EHIS avaandmetest õppekava uuendamine', $message);
}
