<?php

/**
 * @file
 * Contains htm_custom_oska.module.
 */

use Drupal\Core\Routing\RouteMatchInterface;

/**
 * Implements hook_help().
 */
function htm_custom_oska_help($route_name, RouteMatchInterface $route_match) {
  #test
  switch ($route_name) {
    // Main module help for the htm_custom_oska module.
    case 'help.page.htm_custom_oska':
      $output = '';
      $output .= '<h3>' . t('About') . '</h3>';
      $output .= '<p>' . t('Module for OSKA graphs') . '</p>';
      return $output;

    default:
  }
}
