<?php

/**
 * @file
 * Contains htm_custom_tara_authentication.module.
 */

use Drupal\user\UserInterface;

function htm_custom_tara_authentication_openid_connect_userinfo_alter(array &$userinfo, array $context) {
	//@TODO we need to change email
	$sub = $context['user_data']['sub'];

	dump($context);

	$userinfo['email'] = "$sub@HTMportaal.ee";
	#$userinfo['email'] = "$sub@HTMportaal.ee";
	$userinfo['id_code'] = substr($sub, 2);
}

function htm_custom_tara_authentication_openid_connect_claims_alter(&$claims){
	$claims['id_code'] = [
		'scope' => 'profile',
		'title' => 'ID code',
		'type' => 'string',
		'description' => 'ID code',
	];
}



