<?php

function htm_custom_tara_authentication_openid_connect_userinfo_alter(array &$userinfo, array $context) {
	//@TODO we need to change email
	$sub = $context['user_data']['sub'];
	#dump($userinfo);
	#dump($context);
	#die();
	$userinfo['email'] = "$sub@HTMportaal.ee";
	#$userinfo['email'] = "$sub@HTMportaal.ee";
	if($context['user_data']['iss'] === 'https://test.harid.ee'){
	  dump($userinfo);
	  dump($context);
	  die();
		$userinfo['id_code'] = preg_replace("/[^0-9]/", "", $userinfo['personal_code']);
	}else{
		$userinfo['id_code'] = substr($sub, 2);
	}
	if(isset($userinfo['profile_attributes'])){
    foreach($userinfo['profile_attributes'] as $field => $value){
      $userinfo[$field] = $value;
    }
  }
}

function htm_custom_tara_authentication_openid_connect_claims_alter(&$claims){
	$claims['id_code'] = [
		'scope' => 'profile',
		'title' => 'ID code',
		'type' => 'string',
		'description' => 'ID code',
	];
}



