<?php

/**
 * @file
 * Contains htm_custom_xjson_services.module.
 */

use Drupal\Core\Routing\RouteMatchInterface;
use Drupal\Component\Utility\Unicode;

/**
 * Implements hook_help().
 */
function htm_custom_xjson_services_help($route_name, RouteMatchInterface $route_match) {
  switch ($route_name) {
    // Main module help for the htm_custom_xjson_services module.
    case 'help.page.htm_custom_xjson_services':
      $output = '';
      $output .= '<h3>' . t('About') . '</h3>';
      $output .= '<p>' . t('My Awesome Module') . '</p>';
      return $output;

    default:
  }
}

/**
 * Implements hook_mail().
 */
function htm_custom_xjson_services_mail($key, &$message, $params) {

    switch ($key) {
        case 'xjson_email':

            $title = $params['subject'];
            $body = $params['body'];

            $message['headers']['Content-Type'] = 'text/html; charset=UTF-8; format=flowed; delsp=yes';
            $message['from'] = \Drupal::config('system.site')->get('mail');
            $message['subject'] = Unicode::mimeHeaderEncode($title);
            $message['body'][] = $body;

            break;
    }

}