<?php

/**
 * @file
 * Contains htm_custom_ehis_connector.module.
 */

/**
 * Implements hook_rest_resource_alter().
 */
function htm_custom_ehis_connector_rest_resource_alter(&$definitions)
{
  dump($definitions);
  if (isset($definitions['entity:node'])) {
    // We want to handle REST requests regarding nodes with our own plugin
    // class.
    //$definitions['entity:node']['class'] = 'Drupal\htm_custom_ehis_connector\Plugin\rest\resource\NodeResource';
  }
}
