<?php

/**
 * @file
 * Contains htm_custom_authentication.module.
 */

use Drupal\Core\Routing\RouteMatchInterface;

	/**
	 * Implements hook_help().
	 */
	function htm_custom_authentication_help($route_name, RouteMatchInterface $route_match) {
	  switch ($route_name) {
	    // Main module help for the htm_custom_authentication module.
	    case 'help.page.htm_custom_authentication':
	      $output = '';
	      $output .= '<h3>' . t('About') . '</h3>';
	      $output .= '<p>' . t('Module for authenticating over mobile id') . '</p>';
	      return $output;

	    default:
	  }
	}


	/**
	 * @param $length
	 * @return string
	 */
	function getToken($length){
		$token = "";
		$token=strToHex(generateRandomString($length));
		return $token;
	}


	/**
	 * @param $string
	 * @return string
	 */
	function strToHex($string){
		$hex = '';
		for ($i=0; $i<strlen($string); $i++){
			$ord = ord($string[$i]);
			$hexCode = dechex($ord);
			$hex .= substr('0'.$hexCode, -2);
		}
		return strToUpper($hex);
	}


	/**
	 * @param $length
	 * @return string
	 */
	function generateRandomString($length) {
		$characters = '0123456789abcdefghijklmnopqrstuvwxyzABCDEFGHIJKLMNOPQRSTUVWXYZ';
		$charactersLength = strlen($characters);
		$randomString = "";
		for ($i = 0; $i < $length; $i++) {
			$randomString .= $characters[rand(0, $charactersLength - 1)];
		}
		return $randomString;
	}
