export * from './article/article.component';
export * from './frontpage/frontpage.component';
export * from './events/events.component';
export * from './news/news.component';
export * from './news.single/news.single.component';
export * from './events.single/events.single.component';
export * from './personalData/personalData.component';
export * from './schools/schools.component';
export * from './studyProgramme/studyProgramme.component';