version: '3.7'

services:
  postgres:
    container_name: postgres
    image: hub.wiseman.ee/htm/db
    networks:
      - htm
    restart: always
    env_file:
      - postgres.env
    volumes:
      - /root/data/postgres:/var/lib/postgresql/data
  angular:
    container_name: angular
    image: harbor.twn.zone/haridusportaal/angular:develop
    networks:
      - htm
    restart: always
    depends_on:
      - postgres
  swag:
    container_name: swag
    image: linuxserver/swag
    networks:
      - htm
    restart: unless-stopped
    env_file:
      - swag.env
    volumes:
      - /etc/config:/config
    depends_on:
      - angular
  nginx:
    container_name: nginx
    image: nginx:1.15
    networks:
      - htm
    restart: always
    depends_on:
      - swag
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - /etc/nginx:/etc/nginx
      - /etc/nginx/certs/fullchain.pem:/etc/ssl/private/fullchain.pem
      - /etc/nginx/certs/privkey.pem:/etc/ssl/private/privkey.pem

networks:
  htm:
